<?php
include_once 'partial/head.php';
session_start();
if (isset($_POST['add_money'])) {
    $new_amount = mysqli_real_escape_string($con, $_POST['amount_add']);

    if (isset($_SESSION['email'])) {
        $email = $_SESSION['email'];
    } else {
        echo "<script>alert('Login');
            window.location.assign('login.php');
            </script>";
    }

    $sql = "SELECT * FROM user WHERE email='$email';";
    $result = mysqli_query($con, $sql);
    $resultch = mysqli_num_rows($result);
    $row = mysqli_fetch_assoc($result);
    $username = $row['username'];
    $email1 = $row['email'];
    $phone = $row['phone'];
    $address = $row['address'];


    
    $api = "rzp_test_eTk38MV4pvq0dA";

?>
    <script>
        window.onload = function() {
            document.getElementsByName('data-buttontext').click();
        }
    </script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <form action="user_dash.php" method="POST">
        <input type="hidden" name="payment_done" value="<?php echo $new_amount;?>">
        <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="<?php echo $api; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys data-amount="<?php echo $new_amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account data-id="<?php echo 'LOTTI' . rand(10, 100); ?>"//Replace with the order_id generated by you in the backend. data-buttontext="jjj" data-name="Lotti" data-description="Add Money" data-image="https://vast-sierra-59108.herokuapp.com/img/logo2.png" data-prefill.name="<?php echo $username; ?>" data-prefill.email="<?php echo $email1 ?>" data-prefill.contact="<?php echo $phone ?>" data-theme.color="#e57373">
        </script>
        <input type="hidden" custom="Hidden Element" name="hidden">
    </form>


<?php
}
?>
<script>
    $(document).ready(function() {
        $('.razorpay-payment-button').click();
    });
</script>
<style>
    .razorpay-payment-button {
        display: none;
    }
</style>